# Generated by Django 5.2.17 on 2026-09-23 03:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpressRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "recipient_kind",
                    models.CharField(
                        choices=[("CUSTOMER", "普通客户"), ("PROXY_RECIPIENT", "代理临时收件人")],
                        max_length=24,
                    ),
                ),
                ("service_date", models.DateField(db_index=True)),
                ("round_no", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "进行中"), ("CLOSED", "已关闭")],
                        db_index=True,
                        default="OPEN",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="express_rounds",
                        to="customers.customer",
                    ),
                ),
                (
                    "proxy_recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="express_rounds",
                        to="agents.proxyrecipient",
                    ),
                ),
            ],
            options={
                "ordering": ["-service_date", "-round_no", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("EXPRESS", "快递代取"),
                            ("TAKEOUT", "校门口外卖"),
                            ("KFC", "周四 KFC"),
                            ("GROCERY", "果蔬零食"),
                            ("ERRAND", "跑腿送东西"),
                            ("LUGGAGE_UPSTAIRS", "行李搬上楼"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "sequence_date",
                    models.DateField(db_index=True, default=django.utils.timezone.localdate),
                ),
                ("daily_sequence", models.PositiveIntegerField()),
                ("service_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("DIRECT", "普通客户"), ("AGENT", "代理批次")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("NEW", "待接单"),
                            ("ASSIGNED", "已接单"),
                            ("PICKED", "已取到"),
                            ("DELIVERING", "配送中"),
                            ("DELIVERED", "已送达"),
                            ("CANCELED", "已取消"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=16,
                    ),
                ),
                (
                    "settlement_status",
                    models.CharField(
                        choices=[
                            ("UNSETTLED", "未结算"),
                            ("WAITING_PAYMENT", "待付款"),
                            ("SETTLED", "已结算"),
                        ],
                        db_index=True,
                        default="UNSETTLED",
                        max_length=20,
                    ),
                ),
                ("is_urgent", models.BooleanField(db_index=True, default=False)),
                ("requires_upstairs", models.BooleanField(db_index=True, default=False)),
                (
                    "entry_mode",
                    models.CharField(
                        choices=[
                            ("NORMAL", "正常录入"),
                            ("DIRECT_COMPLETE", "快速完成"),
                            ("HISTORICAL_BACKFILL", "历史补录"),
                        ],
                        default="NORMAL",
                        max_length=24,
                    ),
                ),
                (
                    "destination_type",
                    models.CharField(
                        choices=[
                            ("CAMPUS_BUILDING", "校园楼栋"),
                            ("OFF_CAMPUS_ADDRESS", "校外地址"),
                        ],
                        max_length=24,
                    ),
                ),
                ("building_snapshot", models.CharField(blank=True, max_length=80)),
                ("zone_snapshot", models.CharField(blank=True, db_index=True, max_length=16)),
                ("floor_snapshot", models.CharField(blank=True, max_length=20)),
                ("room_snapshot", models.CharField(blank=True, max_length=40)),
                ("off_campus_address", models.CharField(blank=True, max_length=255)),
                ("recipient_name_snapshot", models.CharField(max_length=255)),
                ("recipient_phone_snapshot", models.CharField(blank=True, max_length=100)),
                ("order_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.CharField(blank=True, max_length=255)),
                ("version", models.PositiveIntegerField(default=1)),
                ("soft_deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "canceled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="canceled_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="customers.customer",
                    ),
                ),
                (
                    "proxy_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="agents.proxybatch",
                    ),
                ),
                (
                    "proxy_recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="agents.proxyrecipient",
                    ),
                ),
            ],
            options={
                "ordering": ["-sequence_date", "-daily_sequence", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LuggageUpstairsDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("small_medium_count", models.PositiveIntegerField(default=0)),
                ("large_oversize_count", models.PositiveIntegerField(default=0)),
                (
                    "floor",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("special_pickup_note", models.TextField(blank=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="luggage_detail",
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KfcOrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("pickup_location", models.CharField(max_length=160)),
                ("pickup_code", models.CharField(max_length=128)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kfc_detail",
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroceryOrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("pickup_location", models.CharField(max_length=160)),
                ("item_list", models.TextField()),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grocery_detail",
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpressOrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "pickup_area",
                    models.CharField(
                        choices=[("SOUTH", "南区"), ("NORTH", "北区"), ("OUTSIDE", "校外")],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("outside_pickup_location", models.CharField(blank=True, max_length=160)),
                (
                    "pickup_identifier_type",
                    models.CharField(
                        choices=[
                            ("PICKUP_CODE", "取件码"),
                            ("WAYBILL", "运单号"),
                            ("OTHER", "其他"),
                        ],
                        max_length=16,
                    ),
                ),
                ("pickup_identifier", models.CharField(max_length=255)),
                ("normalized_pickup_identifier", models.CharField(db_index=True, max_length=255)),
                (
                    "size_class",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "未知"),
                            ("SMALL", "小件"),
                            ("MEDIUM", "中件"),
                            ("LARGE", "大件"),
                            ("OVERSIZE", "超大件"),
                        ],
                        db_index=True,
                        default="UNKNOWN",
                        max_length=12,
                    ),
                ),
                (
                    "dispatch_mode",
                    models.CharField(
                        choices=[("ROUTE", "路线配送"), ("DIRECT_CUSTOMER", "客户直送")],
                        default="ROUTE",
                        max_length=20,
                    ),
                ),
                ("small_price_snapshot", models.DecimalField(decimal_places=2, max_digits=8)),
                ("medium_price_snapshot", models.DecimalField(decimal_places=2, max_digits=8)),
                ("large_price_snapshot", models.DecimalField(decimal_places=2, max_digits=8)),
                ("oversize_price_snapshot", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "express_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="express_details",
                        to="orders.expressround",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="express_detail",
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ErrandOrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("pickup_location", models.CharField(max_length=160)),
                ("delivery_location_text", models.CharField(max_length=255)),
                ("item_description", models.TextField()),
                (
                    "size_class",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "未知"),
                            ("SMALL", "小件"),
                            ("MEDIUM", "中件"),
                            ("LARGE", "大件"),
                            ("OVERSIZE", "超大件"),
                        ],
                        default="UNKNOWN",
                        max_length=12,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errand_detail",
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TakeoutOrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "pickup_gate",
                    models.CharField(
                        choices=[("SOUTH_GATE", "南门"), ("NORTH_GATE", "北门"), ("OTHER", "其他")],
                        max_length=16,
                    ),
                ),
                ("other_pickup_location", models.CharField(blank=True, max_length=160)),
                ("identifier", models.CharField(max_length=255)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="takeout_detail",
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="expressround",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("customer__isnull", False),
                        ("proxy_recipient__isnull", True),
                        ("recipient_kind", "CUSTOMER"),
                    ),
                    models.Q(
                        ("customer__isnull", True),
                        ("proxy_recipient__isnull", False),
                        ("recipient_kind", "PROXY_RECIPIENT"),
                    ),
                    _connector="OR",
                ),
                name="orders_express_round_recipient_xor",
            ),
        ),
        migrations.AddConstraint(
            model_name="expressround",
            constraint=models.CheckConstraint(
                condition=models.Q(("round_no__gte", 1)), name="orders_express_round_no_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="expressround",
            constraint=models.UniqueConstraint(
                condition=models.Q(("customer__isnull", False)),
                fields=("customer", "service_date", "round_no"),
                name="orders_unique_customer_express_round_no",
            ),
        ),
        migrations.AddConstraint(
            model_name="expressround",
            constraint=models.UniqueConstraint(
                condition=models.Q(("proxy_recipient__isnull", False)),
                fields=("proxy_recipient", "service_date", "round_no"),
                name="orders_unique_proxy_express_round_no",
            ),
        ),
        migrations.AddConstraint(
            model_name="expressround",
            constraint=models.UniqueConstraint(
                condition=models.Q(("customer__isnull", False), ("status", "OPEN")),
                fields=("customer", "service_date"),
                name="orders_one_open_customer_express_round",
            ),
        ),
        migrations.AddConstraint(
            model_name="expressround",
            constraint=models.UniqueConstraint(
                condition=models.Q(("proxy_recipient__isnull", False), ("status", "OPEN")),
                fields=("proxy_recipient", "service_date"),
                name="orders_one_open_proxy_express_round",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["delivery_status", "business_type", "created_at"],
                name="orders_orde_deliver_880e4b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["source_type", "proxy_batch"], name="orders_orde_source__07c664_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("business_type", "sequence_date", "daily_sequence"),
                name="orders_unique_business_daily_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("daily_sequence__gte", 1)),
                name="orders_daily_sequence_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("customer__isnull", False),
                        ("proxy_batch__isnull", True),
                        ("proxy_recipient__isnull", True),
                        ("source_type", "DIRECT"),
                    ),
                    models.Q(
                        ("business_type", "EXPRESS"),
                        ("customer__isnull", True),
                        ("proxy_batch__isnull", False),
                        ("proxy_recipient__isnull", False),
                        ("source_type", "AGENT"),
                    ),
                    _connector="OR",
                ),
                name="orders_valid_source_recipient",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("business_type", "EXPRESS"), _negated=True),
                    ("service_date__isnull", False),
                    _connector="OR",
                ),
                name="orders_express_service_date_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("business_type", "LUGGAGE_UPSTAIRS"), _negated=True),
                    ("requires_upstairs", True),
                    _connector="OR",
                ),
                name="orders_luggage_requires_upstairs",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("building_snapshot__gt", ""),
                        ("destination_type", "CAMPUS_BUILDING"),
                        ("off_campus_address", ""),
                    ),
                    models.Q(
                        ("destination_type", "OFF_CAMPUS_ADDRESS"), ("off_campus_address__gt", "")
                    ),
                    _connector="OR",
                ),
                name="orders_valid_destination_snapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="luggageupstairsdetail",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("small_medium_count__gt", 0), ("large_oversize_count__gt", 0), _connector="OR"
                ),
                name="orders_luggage_has_items",
            ),
        ),
        migrations.AddConstraint(
            model_name="expressorderdetail",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("outside_pickup_location__gt", ""), ("pickup_area", "OUTSIDE")),
                    models.Q(
                        models.Q(("pickup_area", "OUTSIDE"), _negated=True),
                        ("outside_pickup_location", ""),
                    ),
                    _connector="OR",
                ),
                name="orders_express_outside_location_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="takeoutorderdetail",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("other_pickup_location__gt", ""), ("pickup_gate", "OTHER")),
                    models.Q(
                        models.Q(("pickup_gate", "OTHER"), _negated=True),
                        ("other_pickup_location", ""),
                    ),
                    _connector="OR",
                ),
                name="orders_takeout_other_location_required",
            ),
        ),
    ]
