# Generated by Django 5.2.17 on 2026-10-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_express_dispatch_undecided'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressorderdetail',
            name='size_confirmation_note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
