# Generated by Django 5.2.17 on 2026-09-21 05:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveLoginLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('lease_token_hash', models.CharField(max_length=64)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='accepting_business',
            field=models.CharField(blank=True, choices=[('EXPRESS', '快递代取'), ('TAKEOUT', '校门口外卖'), ('KFC', '周四 KFC'), ('GROCERY', '果蔬零食'), ('ERRAND', '跑腿送东西'), ('LUGGAGE_UPSTAIRS', '行李搬上楼')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='accepting_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='emoji_avatar',
            field=models.CharField(blank=True, default='📦', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', '管理员'), ('RECORDER', '录单员'), ('COURIER', '配送员')], default='COURIER', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='ui_theme',
            field=models.CharField(blank=True, choices=[('light', '亮色'), ('dark', '暗色'), ('warm', '暖色'), ('fresh', '清爽蓝青')], default='', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role', 'COURIER'), models.Q(('accepting_orders', False), ('accepting_business__isnull', True)), _connector='OR'), name='account_non_courier_not_accepting'),
        ),
        migrations.AddField(
            model_name='activeloginlease',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_login_leases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activeloginlease',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_leases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='activeloginlease',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user',), name='account_one_unrevoked_lease_per_user'),
        ),
    ]
