# Generated by Django 5.2.17 on 2026-09-21 05:56

from django.db import migrations

import apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activeloginlease_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
