# Generated by Django 5.2.17 on 2026-09-23 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        ("customers", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryDrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "recipient_kind",
                    models.CharField(
                        choices=[("CUSTOMER", "普通客户"), ("PROXY_RECIPIENT", "代理临时收件人")],
                        max_length=24,
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("EXPRESS", "快递代取"),
                            ("TAKEOUT", "校门口外卖"),
                            ("KFC", "周四 KFC"),
                            ("GROCERY", "果蔬零食"),
                            ("ERRAND", "跑腿送东西"),
                            ("LUGGAGE_UPSTAIRS", "行李搬上楼"),
                        ],
                        max_length=24,
                    ),
                ),
                ("building_snapshot", models.CharField(blank=True, max_length=80)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("RACK", "货架"),
                            ("ROOM", "房间/上楼"),
                            ("HANDOFF", "当面交付"),
                            ("OTHER", "其他"),
                        ],
                        max_length=12,
                    ),
                ),
                ("final_location_text", models.CharField(max_length=255)),
                ("operation_id", models.UUIDField(unique=True)),
                ("delivered_at", models.DateTimeField()),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_drops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_drops",
                        to="customers.customer",
                    ),
                ),
                (
                    "proxy_recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_drops",
                        to="agents.proxyrecipient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryDropItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "drop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="dispatch.deliverydrop",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_drop_items",
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("ROUTE_BATCH", "路线批次"),
                            ("CUSTOMER_DIRECT", "客户直送"),
                            ("SIMPLE", "简单任务"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("EXPRESS", "快递代取"),
                            ("TAKEOUT", "校门口外卖"),
                            ("KFC", "周四 KFC"),
                            ("GROCERY", "果蔬零食"),
                            ("ERRAND", "跑腿送东西"),
                            ("LUGGAGE_UPSTAIRS", "行李搬上楼"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "进行中"),
                            ("COMPLETED", "已完成"),
                            ("CANCELED", "已取消"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("operation_id", models.UUIDField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-accepted_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "end_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COMPLETED", "配送完成"),
                            ("RETURNED", "退回任务池"),
                            ("TRANSFERRED", "已转单"),
                            ("CANCELED", "订单取消"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="orders.order",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="dispatch.deliverytask",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransferRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待接收"),
                            ("ACCEPTED", "已接收"),
                            ("REJECTED", "已拒绝"),
                            ("CANCELED", "已撤回"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("reason_code", models.CharField(blank=True, max_length=40)),
                ("reason_text", models.CharField(max_length=255)),
                ("handoff_required", models.BooleanField(default=False)),
                ("handoff_location", models.CharField(blank=True, max_length=255)),
                ("operation_id", models.UUIDField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "from_courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TransferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_items",
                        to="orders.order",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="dispatch.transferrequest",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="deliverydrop",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("customer__isnull", False),
                        ("proxy_recipient__isnull", True),
                        ("recipient_kind", "CUSTOMER"),
                    ),
                    models.Q(
                        ("customer__isnull", True),
                        ("proxy_recipient__isnull", False),
                        ("recipient_kind", "PROXY_RECIPIENT"),
                    ),
                    _connector="OR",
                ),
                name="dispatch_drop_recipient_xor",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliverydrop",
            constraint=models.CheckConstraint(
                condition=models.Q(("final_location_text", ""), _negated=True),
                name="dispatch_drop_location_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliverydropitem",
            constraint=models.UniqueConstraint(
                fields=("drop", "order"), name="dispatch_unique_drop_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="deliverydropitem",
            constraint=models.UniqueConstraint(
                fields=("order",), name="dispatch_order_delivered_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("order",),
                name="dispatch_one_active_assignment_per_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("end_reason", ""), ("ended_at__isnull", True), ("is_active", True)),
                    models.Q(
                        ("ended_at__isnull", False),
                        ("is_active", False),
                        models.Q(("end_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="dispatch_assignment_end_metadata",
            ),
        ),
        migrations.AddConstraint(
            model_name="transferitem",
            constraint=models.UniqueConstraint(
                fields=("transfer", "order"), name="dispatch_unique_transfer_order"
            ),
        ),
    ]
