# Generated by Django 5.2.17 on 2026-09-23 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dispatch", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "pickup_area",
                    models.CharField(
                        choices=[("SOUTH", "南区"), ("NORTH", "北区"), ("OUTSIDE", "校外")],
                        max_length=12,
                    ),
                ),
                (
                    "destination_zone",
                    models.CharField(
                        choices=[
                            ("SOUTH", "南区"),
                            ("NORTH", "北区"),
                            ("OUTSIDE", "校外"),
                            ("MIXED", "混合"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="route_batch",
                        to="dispatch.deliverytask",
                    ),
                ),
            ],
        ),
    ]
