# Generated by Django 5.2.17 on 2026-09-25 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        ("customers", "0001_initial"),
        ("mediafiles", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsolidationRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "recipient_kind",
                    models.CharField(
                        choices=[("CUSTOMER", "普通客户"), ("PROXY_RECIPIENT", "代理临时收件人")],
                        max_length=24,
                    ),
                ),
                ("round_no", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待归拢"),
                            ("IN_PROGRESS", "归拢中"),
                            ("COMPLETED", "已完成"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "created_mode",
                    models.CharField(choices=[("AUTO", "自动"), ("MANUAL", "人工")], max_length=12),
                ),
                ("frozen_at", models.DateTimeField()),
                ("final_location_text", models.CharField(blank=True, max_length=255)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("completion_operation_id", models.UUIDField(blank=True, null=True, unique=True)),
                (
                    "assigned_courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_consolidation_rounds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consolidation_rounds",
                        to="customers.customer",
                    ),
                ),
                (
                    "express_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consolidation_rounds",
                        to="orders.expressround",
                    ),
                ),
                (
                    "final_far_annotated_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consolidation_annotated_rounds",
                        to="mediafiles.mediafile",
                    ),
                ),
                (
                    "final_far_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consolidation_far_rounds",
                        to="mediafiles.mediafile",
                    ),
                ),
                (
                    "final_near_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consolidation_near_rounds",
                        to="mediafiles.mediafile",
                    ),
                ),
                (
                    "proxy_recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consolidation_rounds",
                        to="agents.proxyrecipient",
                    ),
                ),
            ],
            options={
                "ordering": ["express_round_id", "round_no"],
            },
        ),
        migrations.CreateModel(
            name="ConsolidationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "found_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待查找"),
                            ("FOUND", "已找到"),
                            ("CUSTOMER_TAKEN", "客户已取"),
                            ("EXCEPTION", "人工处置"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("found_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consolidation_item",
                        to="orders.order",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="consolidation.consolidationround",
                    ),
                ),
            ],
            options={
                "ordering": ["order_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="consolidationround",
            constraint=models.UniqueConstraint(
                fields=("express_round", "round_no"), name="consolidation_round_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="consolidationround",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("customer__isnull", False),
                        ("proxy_recipient__isnull", True),
                        ("recipient_kind", "CUSTOMER"),
                    ),
                    models.Q(
                        ("customer__isnull", True),
                        ("proxy_recipient__isnull", False),
                        ("recipient_kind", "PROXY_RECIPIENT"),
                    ),
                    _connector="OR",
                ),
                name="consolidation_recipient_xor",
            ),
        ),
    ]
