# Generated by Django 5.2.17 on 2026-10-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidationitem',
            name='handling_note',
            field=models.TextField(blank=True),
        ),
    ]
