# Generated by Django 5.2.17 on 2026-09-21 15:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_center', '0004_alter_businesstypeconfig_base_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('contact_text', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProxyBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('sequence', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('OPEN', '录入中'), ('READY_TO_SETTLE', '待结算'), ('SETTLED', '已结算'), ('CANCELED', '已取消')], db_index=True, default='OPEN', max_length=24)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proxy_batches', to='agents.agent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proxy_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-batch_date', '-sequence', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProxyRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('recipient_names', models.CharField(blank=True, max_length=255)),
                ('wechat_nickname', models.CharField(blank=True, max_length=100)),
                ('phone_suffixes', models.CharField(blank=True, max_length=100)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('room', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('show_price_on_receipt', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proxy_recipients', to='config_center.building')),
                ('proxy_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='agents.proxybatch')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='proxybatch',
            constraint=models.UniqueConstraint(fields=('agent', 'batch_date', 'sequence'), name='agents_unique_batch_sequence_per_agent_date'),
        ),
        migrations.AddConstraint(
            model_name='proxybatch',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='agents_proxy_batch_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='proxyrecipient',
            constraint=models.UniqueConstraint(fields=('proxy_batch', 'display_name'), name='agents_unique_recipient_name_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='proxyrecipient',
            constraint=models.CheckConstraint(condition=models.Q(('display_name', ''), _negated=True), name='agents_proxy_recipient_name_not_empty'),
        ),
    ]
