# Generated by Django 5.2.17 on 2026-09-23 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exceptions", "0001_initial"),
        ("mediafiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exceptioncaseattachment",
            name="media",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exception_attachments",
                to="mediafiles.mediafile",
            ),
        ),
        migrations.AddField(
            model_name="exceptionevidencelink",
            name="delivery_evidence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exception_links",
                to="mediafiles.deliveryevidence",
            ),
        ),
        migrations.AddField(
            model_name="exceptionevidencelink",
            name="exception_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evidence_links",
                to="exceptions.exceptioncase",
            ),
        ),
        migrations.AddField(
            model_name="exceptionevidencelink",
            name="media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exception_evidence_links",
                to="mediafiles.mediafile",
            ),
        ),
    ]
