# Generated by Django 5.2.17 on 2026-09-25 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consolidation", "0001_initial"),
        ("exceptions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exceptioncase",
            name="consolidation_round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exception_cases",
                to="consolidation.consolidationround",
            ),
        ),
    ]
