# Generated by Django 5.2.17 on 2026-09-28 11:57

import uuid

from django.db import migrations, models


def populate_exception_operation_ids(apps, schema_editor):
    """Assign a distinct idempotency key to every historical exception case."""
    case_model = apps.get_model("exceptions", "ExceptionCase")
    for case in case_model.objects.filter(operation_id__isnull=True).iterator():
        case.operation_id = uuid.uuid4()
        case.save(update_fields=["operation_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('exceptions', '0003_exceptioncase_consolidation_round'),
        ('mediafiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptioncase',
            name='operation_id',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.RunPython(populate_exception_operation_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='exceptioncase',
            name='operation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name='exceptioncaseattachment',
            constraint=models.UniqueConstraint(fields=('exception_case', 'media'), name='exceptions_unique_case_attachment'),
        ),
        migrations.AddConstraint(
            model_name='exceptionevidencelink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('delivery_evidence__isnull', False), ('media__isnull', True)), models.Q(('delivery_evidence__isnull', True), ('media__isnull', False)), _connector='OR'), name='exceptions_evidence_link_xor'),
        ),
        migrations.AddConstraint(
            model_name='exceptionevidencelink',
            constraint=models.UniqueConstraint(fields=('exception_case', 'delivery_evidence'), name='exceptions_unique_case_delivery_evidence'),
        ),
        migrations.AddConstraint(
            model_name='exceptionevidencelink',
            constraint=models.UniqueConstraint(fields=('exception_case', 'media'), name='exceptions_unique_case_media_evidence'),
        ),
    ]
