# Generated by Django 5.2.17 on 2026-09-29 16:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_routebatch'),
        ('exceptions', '0004_exceptioncase_operation_id_and_more'),
        ('orders', '0004_order_creation_fingerprint'),
        ('settlements', '0004_alter_financialadjustment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualHandling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action_type', models.CharField(choices=[('ADD_EXTRA_CHARGE', '追加费用'), ('REDUCE_CHARGE', '减少费用'), ('WAIVE_CHARGE', '费用全免'), ('FULL_REFUND', '全额退款'), ('PARTIAL_REFUND', '部分退款'), ('REDELIVERY', '重新配送'), ('POST_PICKUP_CANCEL', '取件后取消'), ('CUSTOMER_RESOLVED', '客户自行解决'), ('OFFLINE_SETTLEMENT', '线下结算'), ('INFO_CORRECTION', '信息更正'), ('OTHER', '其他')], max_length=32)),
                ('reason', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_manual_handlings', to=settings.AUTH_USER_MODEL)),
                ('delivery_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_handlings', to='dispatch.deliverytask')),
                ('exception_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_handlings', to='exceptions.exceptioncase')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_handlings', to='orders.order')),
                ('resulting_charge_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_handlings', to='settlements.chargeitem')),
                ('resulting_financial_adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_handlings', to='settlements.financialadjustment')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_handlings', to='settlements.settlement')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
