# Generated by Django 5.2.17 on 2026-09-23 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        ("customers", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChargeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[("ORDER", "订单"), ("SETTLEMENT", "结算")], max_length=16
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("BASE_SERVICE", "基础服务费"),
                            ("OFF_CAMPUS_PICKUP", "校外取件费"),
                            ("CAMPUS_TO_OFF_CAMPUS", "校内送校外费"),
                            ("URGENT", "加急费"),
                            ("WEATHER", "特殊天气费"),
                            ("UPSTAIRS", "上楼费"),
                            ("CUSTOMER_EXTRA", "客户自愿加价"),
                            ("MANUAL_SURCHARGE", "人工增费"),
                            ("MANUAL_DISCOUNT", "人工减免"),
                            ("MULTI_ITEM_DISCOUNT", "多件优惠"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("label", models.CharField(max_length=160)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "source",
                    models.CharField(
                        choices=[("SYSTEM_RULE", "系统规则"), ("USER_ADDED", "人工添加")],
                        max_length=16,
                    ),
                ),
                ("config_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "beneficiary_type",
                    models.CharField(
                        choices=[
                            ("PLATFORM", "平台"),
                            ("COURIER", "配送员"),
                            ("NONE", "无收益归属"),
                        ],
                        default="PLATFORM",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "有效"), ("VOIDED", "已作废")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, max_length=255)),
                (
                    "beneficiary_courier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beneficiary_charge_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_charge_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charge_items",
                        to="customers.customer",
                    ),
                ),
                (
                    "express_round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charge_items",
                        to="orders.expressround",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charge_items",
                        to="orders.order",
                    ),
                ),
                (
                    "proxy_recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charge_items",
                        to="agents.proxyrecipient",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voided_charge_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("EXPRESS", "快递代取"),
                            ("TAKEOUT", "校门口外卖"),
                            ("KFC", "周四 KFC"),
                            ("GROCERY", "果蔬零食"),
                            ("ERRAND", "跑腿送东西"),
                            ("LUGGAGE_UPSTAIRS", "行李搬上楼"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "party_type",
                    models.CharField(
                        choices=[("CUSTOMER", "普通客户"), ("AGENT", "代理人")], max_length=16
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草稿"),
                            ("WAITING_PAYMENT", "待付款"),
                            ("SETTLED", "已结算"),
                            ("VOIDED", "已作废"),
                            ("REVERSED", "已撤销"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("frozen_at", models.DateTimeField(blank=True, null=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, max_length=255)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "amount_due_snapshot",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="agents.agent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_settlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="customers.customer",
                    ),
                ),
                (
                    "proxy_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="agents.proxybatch",
                    ),
                ),
                (
                    "settled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settled_settlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voided_settlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="FinancialAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("REFUND", "退款"),
                            ("DISCOUNT_AFTER_SETTLEMENT", "结算后减免"),
                            ("EXTRA_AFTER_SETTLEMENT", "结算后补收"),
                            ("SETTLEMENT_REVERSAL", "误结算撤销"),
                        ],
                        max_length=32,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reason", models.CharField(max_length=255)),
                ("impact_wage", models.BooleanField(default=False)),
                (
                    "wage_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_financial_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wage_courier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wage_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="settlements.settlement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourierEarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("earning_key", models.CharField(max_length=180, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("BASE_DELIVERY", "基础配送"),
                            ("UPSTAIRS", "上楼服务"),
                            ("CUSTOMER_EXTRA", "客户自愿加价"),
                            ("MANUAL_EXTRA", "人工额外服务"),
                            ("WAGE_ADJUSTMENT", "工资调整"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "amount_base",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "commission_rate_snapshot",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
                ),
                (
                    "suggested_wage_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_PAYMENT", "待客户付款"),
                            ("SETTLED", "已结算"),
                            ("REVERSED", "已撤销"),
                        ],
                        db_index=True,
                        default="PENDING_PAYMENT",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courier_earnings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courier_earnings",
                        to="orders.order",
                    ),
                ),
                (
                    "source_charge_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courier_earnings",
                        to="settlements.chargeitem",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courier_earnings",
                        to="settlements.settlement",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="chargeitem",
            name="settlement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="charge_items",
                to="settlements.settlement",
            ),
        ),
        migrations.CreateModel(
            name="SettlementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("BASE_SERVICE", "基础服务费"),
                            ("OFF_CAMPUS_PICKUP", "校外取件费"),
                            ("CAMPUS_TO_OFF_CAMPUS", "校内送校外费"),
                            ("URGENT", "加急费"),
                            ("WEATHER", "特殊天气费"),
                            ("UPSTAIRS", "上楼费"),
                            ("CUSTOMER_EXTRA", "客户自愿加价"),
                            ("MANUAL_SURCHARGE", "人工增费"),
                            ("MANUAL_DISCOUNT", "人工减免"),
                            ("MULTI_ITEM_DISCOUNT", "多件优惠"),
                        ],
                        max_length=32,
                    ),
                ),
                ("label", models.CharField(max_length=160)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "source",
                    models.CharField(
                        choices=[("SYSTEM_RULE", "系统规则"), ("USER_ADDED", "人工添加")],
                        max_length=16,
                    ),
                ),
                ("config_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "beneficiary_type",
                    models.CharField(
                        choices=[
                            ("PLATFORM", "平台"),
                            ("COURIER", "配送员"),
                            ("NONE", "无收益归属"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "beneficiary_courier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beneficiary_settlement_lines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_lines",
                        to="customers.customer",
                    ),
                ),
                (
                    "express_round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_lines",
                        to="orders.expressround",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_lines",
                        to="orders.order",
                    ),
                ),
                (
                    "proxy_recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_lines",
                        to="agents.proxyrecipient",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="settlements.settlement",
                    ),
                ),
                (
                    "source_charge_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_lines",
                        to="settlements.chargeitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SettlementOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_orders",
                        to="orders.order",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_orders",
                        to="settlements.settlement",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="settlement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("agent__isnull", True),
                        ("customer__isnull", False),
                        ("party_type", "CUSTOMER"),
                        ("proxy_batch__isnull", True),
                    ),
                    models.Q(
                        ("agent__isnull", False),
                        ("customer__isnull", True),
                        ("party_type", "AGENT"),
                        ("proxy_batch__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="settlements_party_xor",
            ),
        ),
        migrations.AddConstraint(
            model_name="settlement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount_due_snapshot__isnull", True),
                    ("amount_due_snapshot__gte", 0),
                    _connector="OR",
                ),
                name="settlements_nonnegative_frozen_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="chargeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("order__isnull", False),
                        ("scope_type", "ORDER"),
                        ("settlement__isnull", True),
                    ),
                    models.Q(
                        ("order__isnull", True),
                        ("scope_type", "SETTLEMENT"),
                        ("settlement__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="settlements_charge_scope_binding",
            ),
        ),
        migrations.AddConstraint(
            model_name="chargeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status", "ACTIVE"),
                        ("void_reason", ""),
                        ("voided_at__isnull", True),
                        ("voided_by__isnull", True),
                    ),
                    models.Q(
                        ("status", "VOIDED"),
                        ("void_reason__gt", ""),
                        ("voided_at__isnull", False),
                        ("voided_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="settlements_charge_void_metadata",
            ),
        ),
        migrations.AddConstraint(
            model_name="chargeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("beneficiary_courier__isnull", False), ("beneficiary_type", "COURIER")
                    ),
                    models.Q(
                        models.Q(("beneficiary_type", "COURIER"), _negated=True),
                        ("beneficiary_courier__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="settlements_charge_beneficiary_binding",
            ),
        ),
        migrations.AddConstraint(
            model_name="chargeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("amount__lte", 0),
                        ("charge_type__in", ["MANUAL_DISCOUNT", "MULTI_ITEM_DISCOUNT"]),
                    ),
                    models.Q(
                        models.Q(
                            ("charge_type__in", ["MANUAL_DISCOUNT", "MULTI_ITEM_DISCOUNT"]),
                            _negated=True,
                        ),
                        ("amount__gte", 0),
                    ),
                    _connector="OR",
                ),
                name="settlements_charge_amount_sign",
            ),
        ),
        migrations.AddConstraint(
            model_name="chargeitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("scope_type", "ORDER"), ("source", "SYSTEM_RULE"), ("status", "ACTIVE")
                ),
                fields=("order", "charge_type"),
                name="settlements_one_active_system_charge_type_per_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="settlementline",
            constraint=models.UniqueConstraint(
                fields=("settlement", "source_charge_item"), name="settlements_unique_frozen_charge"
            ),
        ),
        migrations.AddConstraint(
            model_name="settlementorder",
            constraint=models.UniqueConstraint(
                fields=("settlement", "order"), name="settlements_unique_order_membership"
            ),
        ),
    ]
