# Generated by Django 5.2.17 on 2026-09-25 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0001_initial"),
        ("mediafiles", "0001_initial"),
        ("settlements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlement",
            name="build_operation_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="ProxyRecipientReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version_no", models.PositiveIntegerField()),
                ("show_price", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proxy_recipient_receipts",
                        to="mediafiles.mediafile",
                    ),
                ),
                (
                    "proxy_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipient_receipts",
                        to="agents.proxybatch",
                    ),
                ),
                (
                    "proxy_recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="agents.proxyrecipient",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proxy_recipient_receipts",
                        to="settlements.settlement",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("proxy_recipient", "version_no"),
                        name="settlements_unique_proxy_receipt_version",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SettlementImageVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version_no", models.PositiveIntegerField()),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("CUSTOMER_SETTLEMENT", "普通客户结算图"),
                            ("AGENT_SUMMARY", "代理批次汇总图"),
                        ],
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_image_versions",
                        to="mediafiles.mediafile",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="image_versions",
                        to="settlements.settlement",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("settlement", "image_type", "version_no"),
                        name="settlements_unique_image_version",
                    ),
                ],
            },
        ),
    ]
