# Generated by Django 5.2.17 on 2026-09-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('mediafiles', '0001_initial'),
        ('settlements', '0002_settlement_build_operation_id_proxyrecipientreceipt_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='proxyrecipientreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('proxy_recipient',), name='settlements_one_active_proxy_receipt'),
        ),
        migrations.AddConstraint(
            model_name='settlementimageversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('settlement', 'image_type'), name='settlements_one_active_image_type'),
        ),
    ]
