# Generated by Django 5.2.17 on 2026-09-28 06:33

import uuid

from django.db import migrations, models


def populate_adjustment_operation_ids(apps, schema_editor):
    """Give each historical append-only row its own retry-safe identifier."""
    adjustment_model = apps.get_model("settlements", "FinancialAdjustment")
    for adjustment in adjustment_model.objects.filter(operation_id__isnull=True).iterator():
        adjustment.operation_id = uuid.uuid4()
        adjustment.save(update_fields=["operation_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("settlements", "0003_proxyrecipientreceipt_settlements_one_active_proxy_receipt_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="financialadjustment",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddField(
            model_name="financialadjustment",
            name="operation_id",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.RunPython(populate_adjustment_operation_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="financialadjustment",
            name="operation_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
