# Generated by Django 5.2.17 on 2026-09-28 17:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(choices=[('daily_backup', '每日备份'), ('monthly_media_cleanup', '月度媒体清理'), ('stale_login_cleanup', '过期登录清理'), ('tmp_cleanup', '临时文件清理'), ('startup_recovery', '启动恢复检查'), ('restore', '备份恢复')], db_index=True, max_length=40)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('RUNNING', '执行中'), ('SUCCEEDED', '成功'), ('FAILED', '失败')], db_index=True, default='RUNNING', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_summary', models.CharField(blank=True, max_length=500)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('job_name', 'idempotency_key'), name='operations_unique_job_idempotency_key'), models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('status', 'RUNNING')), models.Q(('error_summary', ''), ('finished_at__isnull', False), ('status', 'SUCCEEDED')), models.Q(('finished_at__isnull', False), ('status', 'FAILED')), _connector='OR'), name='operations_job_completion_metadata')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(db_index=True, default=False)),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('backup_type', models.CharField(choices=[('AUTO', '自动备份'), ('MANUAL', '手动备份'), ('PRE_RESTORE', '恢复前保护备份')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('CREATING', '创建中'), ('READY', '可用'), ('FAILED', '失败')], db_index=True, default='CREATING', max_length=12)),
                ('storage_name', models.CharField(max_length=120, unique=True)),
                ('database_size', models.PositiveBigIntegerField(default=0)),
                ('config_size', models.PositiveBigIntegerField(default=0)),
                ('photo_archive_status', models.CharField(choices=[('INCLUDED', '已包含'), ('EMPTY', '无照片'), ('DELETED', '照片归档已清理'), ('FAILED', '归档失败')], default='EMPTY', max_length=12)),
                ('photo_archive_size', models.PositiveBigIntegerField(default=0)),
                ('total_size', models.PositiveBigIntegerField(default=0)),
                ('manifest_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_summary', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status', 'CREATING')), models.Q(('completed_at__isnull', False), ('error_summary', ''), ('status', 'READY')), models.Q(('completed_at__isnull', False), ('status', 'FAILED')), _connector='OR'), name='operations_backup_completion_metadata')],
            },
        ),
    ]
