# Generated by Django 5.2.17 on 2026-09-21 05:55

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('zone', models.CharField(choices=[('SOUTH', '南区'), ('NORTH', '北区')], max_length=8)),
                ('route_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['route_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BusinessTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('EXPRESS', '快递代取'), ('TAKEOUT', '校门口外卖'), ('KFC', '周四 KFC'), ('GROCERY', '果蔬零食'), ('ERRAND', '跑腿送东西'), ('LUGGAGE_UPSTAIRS', '行李搬上楼')], max_length=24, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('display_name', models.CharField(max_length=40)),
                ('icon', models.CharField(blank=True, max_length=16)),
                ('color', models.CharField(default='#2456a6', max_length=16)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('urgent_supported', models.BooleanField(default=True)),
                ('urgent_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
            ],
            options={
                'ordering': ['sort_order', 'business_type'],
            },
        ),
        migrations.CreateModel(
            name='QuickLocationPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'text'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('express_small_price', models.DecimalField(decimal_places=2, default=2, max_digits=8)),
                ('express_medium_price', models.DecimalField(decimal_places=2, default=4, max_digits=8)),
                ('express_large_price', models.DecimalField(decimal_places=2, default=6, max_digits=8)),
                ('express_oversize_price', models.DecimalField(decimal_places=2, default=8, max_digits=8)),
                ('outside_pickup_fee', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('campus_to_outside_fee', models.DecimalField(decimal_places=2, default=2, max_digits=8)),
                ('upstairs_small_medium_rate', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=8)),
                ('upstairs_large_oversize_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('weather_fee', models.DecimalField(decimal_places=2, default=2, max_digits=8)),
                ('multi_item_threshold', models.PositiveSmallIntegerField(default=5)),
                ('multi_item_discount', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=8)),
                ('multi_item_discount_enabled', models.BooleanField(default=True)),
                ('default_theme', models.CharField(choices=[('light', '亮色'), ('dark', '暗色'), ('warm', '暖色'), ('fresh', '清爽蓝青')], default='light', max_length=16)),
                ('kfc_open_weekday', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('heartbeat_interval_seconds', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)])),
                ('lease_stale_seconds', models.PositiveSmallIntegerField(default=150, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(900)])),
                ('media_retention_days', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('EXPRESS', '快递代取'), ('TAKEOUT', '校门口外卖'), ('KFC', '周四 KFC'), ('GROCERY', '果蔬零食'), ('ERRAND', '跑腿送东西'), ('LUGGAGE_UPSTAIRS', '行李搬上楼')], max_length=24)),
                ('earning_source', models.CharField(choices=[('BASE_DELIVERY', '基础配送'), ('UPSTAIRS', '上楼服务'), ('MANUAL_EXTRA', '人工额外服务')], max_length=24)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
            ],
            options={
                'ordering': ['business_type', 'earning_source'],
                'constraints': [models.UniqueConstraint(fields=('business_type', 'earning_source'), name='config_unique_business_earning_commission')],
            },
        ),
    ]
