# Generated by Django 5.2.17 on 2026-09-21 06:04

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0003_seed_v1_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstypeconfig',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='businesstypeconfig',
            name='urgent_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='campus_to_outside_fee',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='express_large_price',
            field=models.DecimalField(decimal_places=2, default=6, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='express_medium_price',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='express_oversize_price',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='express_small_price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='multi_item_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='outside_pickup_fee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='upstairs_large_oversize_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='upstairs_small_medium_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='weather_fee',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
